$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: used-cars-price-endpoint
type: managed
model: azureml:used_cars_price_prediction_model:latest
instance_type: Standard_DS3_v2
instance_count: 1
