name: Train and Deploy CarSales

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true
        pip install jupyter nbconvert scikit-learn pandas numpy mlflow azure-ai-ml

    - name: Set up Azure CLI
      uses: azure/cli@v2
      with:
        inlineScript: |
          az extension remove -n azure-cli-ml || true
          az extension add -n ml -y || true

    - name: Train notebook
      run: |
        echo "Current directory: $(pwd)"
        echo "Listing files:"
        ls -la
        echo "Checking data directory:"
        ls -la data/ || echo "Data directory not found"
        echo "Checking notebooks directory:"
        ls -la notebooks/ || echo "Notebooks directory not found"
        echo "Executing notebook from repository root..."
        jupyter nbconvert --to notebook --execute notebooks/CarSales_Complete_Structured.ipynb --output output-train.ipynb --ExecutePreprocessor.working_directory=.

    - name: Azure ML deploy (best-effort)
      if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      env:
        AZURE_CLIENT_ID:     ${{ secrets.AZ_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
        AZURE_TENANT_ID:     ${{ secrets.AZ_TENANT_ID }}
        AZURE_SUBSCRIPTION:  ${{ secrets.AZ_SUBSCRIPTION }}
        AZURE_RG:            Default_Resource_Group
        AZURE_WS:            GL_AZ_ML
      run: |
        echo "Checking Azure credentials..."
        if [ -z "$AZURE_CLIENT_ID" ] || [ -z "$AZURE_CLIENT_SECRET" ] || [ -z "$AZURE_TENANT_ID" ] || [ -z "$AZURE_SUBSCRIPTION" ]; then
          echo "⚠️ Azure secrets not configured, skipping Azure ML deployment"
          echo "This is expected if secrets are not set up yet"
          exit 0
        fi
        
        echo "Logging in with service principal..."
        az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
        az account set --subscription $AZURE_SUBSCRIPTION

        echo "Register model (skip on failure)..."
        az ml model create --name used_cars_price_prediction_model \
          --type mlflow_model --path local_model \
          -g $AZURE_RG --workspace-name $AZURE_WS || true

        echo "Deploy/update endpoint (skip on failure)..."
        az ml online-endpoint create --file config/endpoint.yml -g $AZURE_RG --workspace-name $AZURE_WS || true
        az ml online-deployment create --file config/deploy.yml -g $AZURE_RG --workspace-name $AZURE_WS --set-traffic blue=100 || true